name: Sync Fork

on:
  schedule:
    - cron: '* 13 * * *' # every day at 13 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PRRTE_SYNC_UPSTREAM_MASTER_ID }}
          owner: openpmix
          base: master
          head: master
          auto_merge: true
          auto_approve: false

          
